Organizations:
    - &OrdererOrg
        Name: OrdererMSP
        ID: OrdererMSP
        MSPDir: ../organizations/ordererOrganizations/example.com/msp

    - &CreatorOrg
        Name: CreatorMSP
        ID: CreatorMSP
        MSPDir: ../organizations/peerOrganizations/creator.example.com/msp

    - &ApproverOrg
        Name: ApproverMSP
        ID: ApproverMSP
        MSPDir: ../organizations/peerOrganizations/approver.example.com/msp

Application: &ApplicationDefaults
    Organizations:

Orderer: &OrdererDefaults
    OrdererType: etcdraft
    EtcdRaft:
        Consenters:
            - Host: orderer.example.com
              Port: 7050
              ClientTLSCert: ../organizations/ordererOrganizations/example.com/orderers/orderer.example.com/tls/server.crt
              ServerTLSCert: ../organizations/ordererOrganizations/example.com/orderers/orderer.example.com/tls/server.crt
    Addresses:
        - orderer.example.com:7050
    BatchTimeout: 2s
    BatchSize:
        MaxMessageCount: 10
        AbsoluteMaxBytes: 99 MB
        PreferredMaxBytes: 512 KB
    Organizations:

Channel: &ChannelDefaults
    Consortium: SampleConsortium

Profiles:
    TwoOrgsOrdererGenesis:
        Orderer:
            <<: *OrdererDefaults
            Organizations:
                - *OrdererOrg
        Consortiums:
            SampleConsortium:
                Organizations:
                    - *CreatorOrg
                    - *ApproverOrg

    TwoOrgsChannel:
        Consortium: SampleConsortium
        Application:
            <<: *ApplicationDefaults
            Organizations:
                - *CreatorOrg
                - *ApproverOrg


